/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tickettravel;

/**
 *
 * @author ASUS
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("VÉ MÁY BAY KHÁCH ĐẶT MỚI NHẤT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(106, 23, 319, 39);

        jLabel2.setText("-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(261, 116, 10, 16);

        jLabel3.setText("Hồ Chí Minh");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(176, 105, 78, 39);

        jLabel4.setText("Đà Nẵng");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(289, 105, 66, 39);

        jLabel5.setText("Khách đặt 1 vé máy bay");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(38, 116, 126, 16);

        jLabel6.setText("Khách đặt 1 vé máy bay");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(38, 189, 126, 28);

        jLabel7.setText("Hồ Chí Minh");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(176, 184, 78, 39);

        jLabel8.setText("-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(261, 195, 10, 16);

        jLabel9.setText("Đà Nẵng");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(289, 262, 66, 39);

        jLabel10.setText("Khách đặt 1 vé máy bay");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(38, 262, 126, 28);

        jLabel11.setText("Hà Nội");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(176, 341, 78, 39);

        jLabel12.setText("Hà Nội");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(289, 184, 66, 39);

        jLabel13.setText("-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(261, 273, 21, 16);

        jLabel14.setText("Khách đặt 1 vé máy bay");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(38, 346, 126, 28);

        jLabel15.setText("Hải Phòng");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(176, 262, 78, 39);

        jLabel16.setText("-");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(261, 352, 21, 16);

        jLabel17.setText("Đà Nẵng");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(289, 341, 66, 39);

        jLabel18.setText("Giá : 1,274,280 đồng/vé");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(176, 151, 124, 26);

        jLabel19.setText("Giá : 3,091,336 đồng/vé");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(176, 308, 133, 26);

        jLabel20.setText("Giá : 2,340,000 đồng/vé");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(176, 230, 124, 26);

        jLabel21.setText("Giá : 1,706,010 đồng/vé");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(176, 387, 124, 26);

        jLabel22.setText("chi tiết");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(359, 156, 43, 16);

        jLabel23.setText("chi tiết");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(359, 240, 43, 16);

        jLabel24.setText("chi tiết");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(359, 313, 43, 16);

        jLabel25.setText("chi tiết");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(359, 392, 43, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
